### ISSUE TITLE
OSError: [Errno 6] Device not configured

### ISSUE THREAD

**Issue by xy-ef** [eht16/python-logstash-async#102]
Hi, I use logstash-async in my project, and got an error ``Device not configured``, but the package [python-logstash](https://pypi.org/project/python-logstash/) works properly. Anybody know what causes this problem?  Thanks.

The code is
```python
# logstash_async doesnot work on my macbook
from logstash_async.handler import AsynchronousLogstashHandler
from logstash_async.formatter import LogstashFormatter

logger = logging.getLogger(logger_name)

logstash_host, logstash_port = get_logstash_config()
logstash_async_handler = AsynchronousLogstashHandler(
    host=logstash_host,
    port=logstash_port,
    database_path=None,
)

logstash_async_formatter = LogstashFormatter(
    message_type="python-logstash",
    extra_prefix="dev"
)

logstash_async_handler.setFormatter(logstash_async_formatter)
logger.addHandler(logstash_async_handler)
```

My computer is 
```
Apple M3 
Mac OS 14.6
```
, and the exception stack is as follows, thanks.
```
2024-12-08 11:05:59: exception: An error occurred while sending events: [Errno 6] Device not configured
Traceback (most recent call last):
  File "/Users/abc.abc/miniconda3/envs/dtc-search-rec/lib/python3.12/site-packages/logstash_async/worker.py", line 138, in _fetch_events
    self._fetch_event()
  File "/Users/abc.abc/miniconda3/envs/dtc-search-rec/lib/python3.12/site-packages/logstash_async/worker.py", line 160, in _fetch_event
    self._event = self._queue.get(block=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/abc.abc/miniconda3/envs/dtc-search-rec/lib/python3.12/queue.py", line 168, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/abc.abc/miniconda3/envs/dtc-search-rec/lib/python3.12/site-packages/logstash_async/worker.py", line 241, in _flush_queued_events
    self._send_events(events)
  File "/Users/abc.abc/miniconda3/envs/dtc-search-rec/lib/python3.12/site-packages/logstash_async/worker.py", line 304, in _send_events
    self._transport.send(events, use_logging=use_logging)
  File "/Users/abc.abc/miniconda3/envs/dtc-search-rec/lib/python3.12/site-packages/logstash_async/transport.py", line 103, in send
    self._close()
  File "/Users/abc.abc/miniconda3/envs/dtc-search-rec/lib/python3.12/site-packages/logstash_async/transport.py", line 137, in _close
    self._wait_for_socket_buffer_empty()
  File "/Users/abc.abc/miniconda3/envs/dtc-search-rec/lib/python3.12/site-packages/logstash_async/transport.py", line 150, in _wait_for_socket_buffer_empty
    while time_waited < wait_timeout and not self._is_sock_write_buff_empty():
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/abc.abc/miniconda3/envs/dtc-search-rec/lib/python3.12/site-packages/logstash_async/transport.py", line 161, in _is_sock_write_buff_empty
    ioctl_result = fcntl.ioctl(socket_fd, termios.TIOCOUTQ, buffer_size)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 6] Device not configured
```

**Comment by sbowman** [comment]
I don't have a solution, but I'm getting the same error.

**Comment by xy-ef** [comment]
Thanks for your reply. Using http is a smart workaround, yet I don't have the luck to be able to change the logstash.conf, which does not accept http connections. Thanks.

**Comment by eht16** [comment]
It seems the mentioned `fcntl.ioctl` call is not support on macOS.

I assumed if `fcntl` can be imported this is enough to check, obviously not.
Since I don't have access to macOS, it's unlike I can work on this.

@xy-ef 
You can set `constants.SOCKET_CLOSE_WAIT_TIMEOUT` to 0, this should bypass the code which causes the error.

**Comment by xy-ef** [comment]
> It seems the mentioned `fcntl.ioctl` call is not support on macOS.
> 
> I assumed if `fcntl` can be imported this is enough to check, obviously not. Since I don't have access to macOS, it's unlike I can work on this.
> 
> @xy-ef You can set `constants.SOCKET_CLOSE_WAIT_TIMEOUT` to 0, this should bypass the code which causes the error.

Thanks for your reply, I'll also see how this can be solved.
