### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by SalahAdDin** [eht16/python-logstash-async#21]
Hi, finally i'm getting this working, it was a hard way but i have it.

Unfortunatelly i have a problem with it:
```bash
xprende.blog     | Traceback (most recent call last):
xprende.blog     |   File "/usr/local/lib/python3.6/site-packages/logstash_async/worker.py", line 118, in _fetch_events
xprende.blog     |     self._fetch_event()
xprende.blog     |   File "/usr/local/lib/python3.6/site-packages/logstash_async/worker.py", line 140, in _fetch_event
xprende.blog     |     self._event = self._queue.get(block=False)
xprende.blog     |   File "/usr/local/lib/python3.6/queue.py", line 161, in get
xprende.blog     |     raise Empty
xprende.blog     | queue.Empty
xprende.blog     | 
xprende.blog     | During handling of the above exception, another exception occurred:
xprende.blog     | 
xprende.blog     | Traceback (most recent call last):
xprende.blog     |   File "/usr/local/lib/python3.6/site-packages/logstash_async/worker.py", line 223, in _flush_queued_events
xprende.blog     |     self._send_events(events)
xprende.blog     |   File "/usr/local/lib/python3.6/site-packages/logstash_async/worker.py", line 253, in _send_events
xprende.blog     |     self._transport.send(events)
xprende.blog     |   File "/usr/local/lib/python3.6/site-packages/logstash_async/transport.py", line 28, in send
xprende.blog     |     self._create_socket()
xprende.blog     |   File "/usr/local/lib/python3.6/site-packages/logstash_async/transport.py", line 94, in _create_socket
xprende.blog     |     sock.connect((self._host, self._port))
xprende.blog     | ConnectionRefusedError: [Errno 111] Connection refused
```

As you can see, the socket can't connect with `logstash`, but i can't understand why.

**Comment by SalahAdDin** [comment]
I forgot this: `'host': 'logstash.host.tld',`
