### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by xNinjaKittyx** [eht16/python-logstash-async#38]
So, sometimes when logstash is down, our long running scripts will report the normal queue.Empty + connectionError.

This is fine, however, when running with pytest, pytest will create an XML file at the end of the test, which fails due to do "Too many open files"

Are failed socket connections somehow lingering for long periods of time?

I also noticed that after long period of failing to connect to logstash, the sqlite3 connections failed (I'm assuming it's because of too many open sockets)

```
error	26-Apr-2019 02:44:43	20190426 02:44:43|worke:[ERROR] - Log processing error (queue size: 1031): unable to open database file
error	26-Apr-2019 02:44:43	Traceback (most recent call last):
error	26-Apr-2019 02:44:43	  File "/home.local/build/.local/share/virtualenvs/<redacted>-rYeAsF95/lib/python3.6/site-packages/logstash_async/worker.py", line 145, in _process_event
error	26-Apr-2019 02:44:43	    self._write_event_to_database()
error	26-Apr-2019 02:44:43	  File "/home.local/build/.local/share/virtualenvs/<redacted>-rYeAsF95/lib/python3.6/site-packages/logstash_async/worker.py", line 195, in _write_event_to_database
error	26-Apr-2019 02:44:43	    self._database.add_event(self._event)
error	26-Apr-2019 02:44:43	  File "/home.local/build/.local/share/virtualenvs/<redacted>-rYeAsF95/lib/python3.6/site-packages/logstash_async/database.py", line 94, in add_event
error	26-Apr-2019 02:44:43	    connection.execute(query, (event, False))
error	26-Apr-2019 02:44:43	sqlite3.OperationalError: unable to open database file
```

Looking at the code, I think this could be fixed by using a connection pool, rather than creating new connections everytime. It would be nice if there was a way to configure this to use a connection pool rather than creating new connections every time.

**Comment by eht16** [comment]
The connection pool sounds like a good idea.
When I find time, I'll probably going to implement it. If anyone else wants to do before, PRs are welcome :).

The "Too many open files" problem should be investigated.
Can you provide an example script or a stripped down version of your pytest suite?

**Comment by xNinjaKittyx** [comment]
The "Too many open files" is most likely because the lingering sockets that are waiting to be closed hit the ulimit of the linux system (hence unable to make any sqlite connections).

My case is really just 1 long running script inside a pytest readable format.
I would assume anyone would do something similar with the following:

- Start logstash_async to a server that doesn't exist.
- Start printing out log statements for a long period of time
- Eventually hit this error(?)

I tried doing this on my windows machine at home w/ using
```
constants.QUEUED_EVENTS_FLUSH_INTERVAL = 1.0
constants.QUEUE_CHECK_INTERVAL = 0.1
constants.SOCKET_TIMEOUT = 0.1
```
but it doesn't seem that easy.

I might have this run for a long period of time on a separate linux VM and see if it runs into the issue..

**Comment by eht16** [comment]
`to a server that doesn't exist` what does this mean exactly? What kind of error do you get in your scenario? Timeouts or `connection refused` or `connection reset` or something else?

I'm currently testing with generating 10000 messages in a loop while trying to send it to a closed port (i.e. `connection refused`) and so far there is no increase in open file handles. Same queue/timeout settings as yours above.

**Comment by xNinjaKittyx** [comment]
Yeah.. I tried the same, and I haven't been getting results.

This error happened when the ELK stack had some down time, and my test script ships the logs over, which were failing. Unfortunately due to company policy, I cannot share my code, but I am trying to find something that will reproduce the issue. Ever since that day, I haven't been able to run into the issue again (I haven't actively tried either).

Looking back at the log again, here's the error that first popped up:
```

**Comment by xNinjaKittyx** [comment]
*sorry I pressed Enter too early for the first part.*

I haven't been able to reproduce this either. Due to company policy, I cannot share my test script, so I'm trying to figure out a way to reproduce this problem.

While running my script, ELK had downtime, which was the specific reason why I ran into this in the first place.

Looking back at the logs, it was spitting this error for a while:

```
error	26-Apr-2019 00:54:02	20190426 00:54:02|worke:[ERROR] - An error occurred while sending events: [Errno 111] Connection refused
error	26-Apr-2019 00:54:02	Traceback (most recent call last):
error	26-Apr-2019 00:54:02	  File "/home.local/build/.local/share/virtualenvs/star-rYeAsF95/lib/python3.6/site-packages/logstash_async/worker.py", line 118, in _fetch_events
error	26-Apr-2019 00:54:02	    self._fetch_event()
error	26-Apr-2019 00:54:02	  File "/home.local/build/.local/share/virtualenvs/star-rYeAsF95/lib/python3.6/site-packages/logstash_async/worker.py", line 140, in _fetch_event
error	26-Apr-2019 00:54:02	    self._event = self._queue.get(block=False)
error	26-Apr-2019 00:54:02	  File "/usr/lib/python3.6/queue.py", line 161, in get
error	26-Apr-2019 00:54:02	    raise Empty
error	26-Apr-2019 00:54:02	queue.Empty
error	26-Apr-2019 00:54:02	
error	26-Apr-2019 00:54:02	During handling of the above exception, another exception occurred:
error	26-Apr-2019 00:54:02	
error	26-Apr-2019 00:54:02	Traceback (most recent call last):
error	26-Apr-2019 00:54:02	  File "/home.local/build/.local/share/virtualenvs/star-rYeAsF95/lib/python3.6/site-packages/logstash_async/worker.py", line 224, in _flush_queued_events
error	26-Apr-2019 00:54:02	    self._send_events(events)
error	26-Apr-2019 00:54:02	  File "/home.local/build/.local/share/virtualenvs/star-rYeAsF95/lib/python3.6/site-packages/logstash_async/worker.py", line 255, in _send_events
error	26-Apr-2019 00:54:02	    self._transport.send(events, use_logging=use_logging)
error	26-Apr-2019 00:54:02	  File "/home.local/build/.local/share/virtualenvs/star-rYeAsF95/lib/python3.6/site-packages/logstash_async/transport.py", line 35, in send
error	26-Apr-2019 00:54:02	    self._create_socket()
error	26-Apr-2019 00:54:02	  File "/home.local/build/.local/share/virtualenvs/star-rYeAsF95/lib/python3.6/site-packages/logstash_async/transport.py", line 114, in _create_socket
error	26-Apr-2019 00:54:02	    sock.connect((self._host, self._port))
error	26-Apr-2019 00:54:02	ConnectionRefusedError: [Errno 111] Connection refused
```

This was expected since logstash was down during this time. This goes on for about 2.5 hours with this error. Then it switches to this:

```
error	26-Apr-2019 02:41:58	20190426 02:41:58|worke:[ERROR] - An unexpected error occurred: unable to open database file
error	26-Apr-2019 02:41:58	Traceback (most recent call last):
error	26-Apr-2019 02:41:58	  File "/home.local/build/.local/share/virtualenvs/star-rYeAsF95/lib/python3.6/site-packages/logstash_async/worker.py", line 118, in _fetch_events
error	26-Apr-2019 02:41:58	    self._fetch_event()
error	26-Apr-2019 02:41:58	  File "/home.local/build/.local/share/virtualenvs/star-rYeAsF95/lib/python3.6/site-packages/logstash_async/worker.py", line 140, in _fetch_event
error	26-Apr-2019 02:41:58	    self._event = self._queue.get(block=False)
error	26-Apr-2019 02:41:58	  File "/usr/lib/python3.6/queue.py", line 161, in get
error	26-Apr-2019 02:41:58	    raise Empty
error	26-Apr-2019 02:41:58	queue.Empty
error	26-Apr-2019 02:41:58	
error	26-Apr-2019 02:41:58	During handling of the above exception, another exception occurred:
error	26-Apr-2019 02:41:58	
error	26-Apr-2019 02:41:58	Traceback (most recent call last):
error	26-Apr-2019 02:41:58	  File "/home.local/build/.local/share/virtualenvs/star-rYeAsF95/lib/python3.6/site-packages/logstash_async/worker.py", line 224, in _flush_queued_events
error	26-Apr-2019 02:41:58	    self._send_events(events)
error	26-Apr-2019 02:41:58	  File "/home.local/build/.local/share/virtualenvs/star-rYeAsF95/lib/python3.6/site-packages/logstash_async/worker.py", line 255, in _send_events
error	26-Apr-2019 02:41:58	    self._transport.send(events, use_logging=use_logging)
error	26-Apr-2019 02:41:58	  File "/home.local/build/.local/share/virtualenvs/star-rYeAsF95/lib/python3.6/site-packages/logstash_async/transport.py", line 35, in send
error	26-Apr-2019 02:41:58	    self._create_socket()
error	26-Apr-2019 02:41:58	  File "/home.local/build/.local/share/virtualenvs/star-rYeAsF95/lib/python3.6/site-packages/logstash_async/transport.py", line 114, in _create_socket
error	26-Apr-2019 02:41:58	    sock.connect((self._host, self._port))
error	26-Apr-2019 02:41:58	ConnectionRefusedError: [Errno 111] Connection refused
error	26-Apr-2019 02:41:58	
error	26-Apr-2019 02:41:58	During handling of the above exception, another exception occurred:
error	26-Apr-2019 02:41:58	
error	26-Apr-2019 02:41:58	Traceback (most recent call last):
error	26-Apr-2019 02:41:58	  File "/home.local/build/.local/share/virtualenvs/star-rYeAsF95/lib/python3.6/site-packages/logstash_async/worker.py", line 76, in run
error	26-Apr-2019 02:41:58	    self._fetch_events()
error	26-Apr-2019 02:41:58	  File "/home.local/build/.local/share/virtualenvs/star-rYeAsF95/lib/python3.6/site-packages/logstash_async/worker.py", line 128, in _fetch_events
error	26-Apr-2019 02:41:58	    self._flush_queued_events(force=force_flush)
error	26-Apr-2019 02:41:58	  File "/home.local/build/.local/share/virtualenvs/star-rYeAsF95/lib/python3.6/site-packages/logstash_async/worker.py", line 231, in _flush_queued_events
error	26-Apr-2019 02:41:58	    self._database.requeue_queued_events(queued_events)
error	26-Apr-2019 02:41:58	  File "/home.local/build/.local/share/virtualenvs/star-rYeAsF95/lib/python3.6/site-packages/logstash_async/database.py", line 128, in requeue_queued_events
error	26-Apr-2019 02:41:58	    self._bulk_update_events(cursor, events, query_update_base)
error	26-Apr-2019 02:41:58	  File "/home.local/build/.local/share/virtualenvs/star-rYeAsF95/lib/python3.6/site-packages/logstash_async/database.py", line 121, in _bulk_update_events
error	26-Apr-2019 02:41:58	    cursor.execute(statement, event_ids_subset)
error	26-Apr-2019 02:41:58	sqlite3.OperationalError: unable to open database file
error	26-Apr-2019 02:41:58	20190426 02:41:58|worke:[ WARN] - Non-empty queue while shutting down (2 events pending). This indicates a previous error.
```


Afterwards, it repeatedly reports this error:

```
error	26-Apr-2019 02:42:01	20190426 02:42:01|worke:[ERROR] - Log processing error (queue size:  14): unable to open database file
error	26-Apr-2019 02:42:01	Traceback (most recent call last):
error	26-Apr-2019 02:42:01	  File "/home.local/build/.local/share/virtualenvs/star-rYeAsF95/lib/python3.6/site-packages/logstash_async/worker.py", line 145, in _process_event
error	26-Apr-2019 02:42:01	    self._write_event_to_database()
error	26-Apr-2019 02:42:01	  File "/home.local/build/.local/share/virtualenvs/star-rYeAsF95/lib/python3.6/site-packages/logstash_async/worker.py", line 195, in _write_event_to_database
error	26-Apr-2019 02:42:01	    self._database.add_event(self._event)
error	26-Apr-2019 02:42:01	  File "/home.local/build/.local/share/virtualenvs/star-rYeAsF95/lib/python3.6/site-packages/logstash_async/database.py", line 94, in add_event
error	26-Apr-2019 02:42:01	    connection.execute(query, (event, False))
error	26-Apr-2019 02:42:01	sqlite3.OperationalError: unable to open database file
```

with the queue size gradually increasing as more logs are printed. (went up to around 20k but didn't crash).

Again, I haven't ran into an issue when logstash was up, so I'm just as confused as to how I got here in the first place. Maybe I'm understanding the errors wrong?

**Comment by eht16** [comment]
I'm not sure either.

So far, I wasn't able to reproduce the described error.
My test script is running for nearly 48 hours now with lingering errors (connection refused) but I cannot see any left open sockets or otherwise an increase in open file descriptors.
Also, after checking the code again, I don't see a place where sockets can be left open.

I don't say there might be a bug in the code, I just don't know where it hides :).

Could you grep your logs for any other errors than the already mentioned ones? Maybe the errors we see are just the symptom but not the cause.

**Comment by xNinjaKittyx** [comment]
I looked closer, and I couldn't find anything particularly different.

I don't think I'm going to be able to reproduce this, so we can close it and revisit if I ever run into it again.

**Comment by eht16** [comment]
Alright, feel free to re-open if you get more information.
