### ISSUE TITLE
Error: queue.Empty

### ISSUE THREAD

**Issue by vitalerter** [eht16/python-logstash-async#62]
Hi,

- I am using logstash-async **without** db
-  i configure python logging handler this way:
```
 handlers:
        console:
            class: logging.StreamHandler
            level: INFO
            stream: ext://sys.stdout
            formatter: simple
        logstash:
            level: DEBUG
            class: logstash_async.handler.AsynchronousLogstashHandler
            formatter: logstash_formatter
            host: logger.vitalerter.com
            port: 5000
            database_path: null
```
- Do you have an idea how to manage this error?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/logstash_async/worker.py", line 118, in _fetch_events
    self._fetch_event()
  File "/usr/local/lib/python3.8/site-packages/logstash_async/worker.py", line 140, in _fetch_event
    self._event = self._queue.get(block=False)
  File "/usr/local/lib/python3.8/queue.py", line 167, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/logstash_async/worker.py", line 214, in _flush_queued_events
    self._send_events(events)
  File "/usr/local/lib/python3.8/site-packages/logstash_async/worker.py", line 268, in _send_events
    self._transport.send(events, use_logging=use_logging)
  File "/usr/local/lib/python3.8/site-packages/logstash_async/transport.py", line 88, in send
    self._create_socket()
  File "/usr/local/lib/python3.8/site-packages/logstash_async/transport.py", line 166, in _create_socket
    self._sock.connect((self._host, self._port))
socket.timeout: timed out
```

**Comment by eht16** [comment]
The real error is: `socket.timeout: timed out`.
Check your configuration and network connectivity to the Logstash server.
